<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Auth\Authentication\Adapter\DbAdapter'               => __DIR__ . '/src/Auth/Authentication/Adapter/DbAdapter.php',
    'Auth\Authentication\Adapter\Model\Identity'          => __DIR__ . '/src/Auth/Authentication/Adapter/Model/Identity.php',
    'Auth\Authentication\Adapter\Model\IdentityInterface' => __DIR__ . '/src/Auth/Authentication/Adapter/Model/IdentityInterface.php',
    'Auth\Authentication\Storage\CacheStorage'            => __DIR__ . '/src/Auth/Authentication/Storage/CacheStorage.php',
    'Auth\Authentication\Storage\AbstractStorage'         => __DIR__ . '/src/Auth/Authentication/Storage/AbstractStorage.php',
    'Auth\Authentication\Storage\Session'                 => __DIR__ . '/src/Auth/Authentication/Storage/Session.php',
    'Auth\Authentication\Storage\StorageInterface'        => __DIR__ . '/src/Auth/Authentication/Storage/StorageInterface.php',
);
