<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Rbac\Service\Rbac'                 => __DIR__ . '/src/Rbac/Service/Rbac.php',
    'Rbac\Db\Service\Permission'        => __DIR__ . '/src/Rbac/Db/Service/Permission.php',
    'Rbac\Db\Service\RoleRelation'      => __DIR__ . '/src/Rbac/Db/Service/RoleRelation.php',
    'Rbac\Db\Service\RolePermission'    => __DIR__ . '/src/Rbac/Db/Service/RolePermission.php',
    'Rbac\Db\Service\Role'              => __DIR__ . '/src/Rbac/Db/Service/Role.php',
    'Rbac\Db\Mapper\Permission'         => __DIR__ . '/src/Rbac/Db/Mapper/Permission.php',
    'Rbac\Db\Mapper\RoleRelation'       => __DIR__ . '/src/Rbac/Db/Mapper/RoleRelation.php',
    'Rbac\Db\Mapper\RolePermission'     => __DIR__ . '/src/Rbac/Db/Mapper/RolePermission.php',
    'Rbac\Db\Mapper\Role'               => __DIR__ . '/src/Rbac/Db/Mapper/Role.php',
    'Rbac\Db\Model\Base\Permission'     => __DIR__ . '/src/Rbac/Db/Model/Base/Permission.php',
    'Rbac\Db\Model\Base\RoleRelation'   => __DIR__ . '/src/Rbac/Db/Model/Base/RoleRelation.php',
    'Rbac\Db\Model\Base\RolePermission' => __DIR__ . '/src/Rbac/Db/Model/Base/RolePermission.php',
    'Rbac\Db\Model\Base\Role'           => __DIR__ . '/src/Rbac/Db/Model/Base/Role.php',
    'Rbac\Db\Model\Permission'          => __DIR__ . '/src/Rbac/Db/Model/Permission.php',
    'Rbac\Db\Model\RoleRelation'        => __DIR__ . '/src/Rbac/Db/Model/RoleRelation.php',
    'Rbac\Db\Model\RolePermission'      => __DIR__ . '/src/Rbac/Db/Model/RolePermission.php',
    'Rbac\Db\Model\Role'                => __DIR__ . '/src/Rbac/Db/Model/Role.php',
);
