-- MySQL Script generated by MySQL Workbench
-- lun. 09 nov. 2015 14:41:40 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apiwow
-- -----------------------------------------------------
-- apiwow

-- -----------------------------------------------------
-- Table `connection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `connection` ;

CREATE TABLE IF NOT EXISTS `connection` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `token` VARCHAR(80) NOT NULL,
  `end` DATETIME NOT NULL,
  `start` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_connection_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_connection_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
