-- MySQL Script generated by MySQL Workbench
-- lun. 31 août 2015 11:55:09 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apiwow
-- -----------------------------------------------------
-- apiwow

-- -----------------------------------------------------
-- Table `conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conversation` ;

CREATE TABLE IF NOT EXISTS `conversation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school` ;

CREATE TABLE IF NOT EXISTS `school` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `next_name` VARCHAR(45) NULL,
  `short_name` TEXT NULL,
  `logo` VARCHAR(80) NULL,
  `describe` TEXT NULL,
  `website` TEXT NULL,
  `programme` TEXT NULL,
  `background` VARCHAR(80) NULL,
  `phone` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `contact_id` INT UNSIGNED NULL,
  `address_id` INT UNSIGNED NULL,
  `deleted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_school_1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(128) NULL,
  `lastname` VARCHAR(128) NULL,
  `status` TEXT NULL,
  `email` VARCHAR(128) NULL,
  `password` VARCHAR(128) NULL,
  `new_password` VARCHAR(128) NULL,
  `birth_date` DATETIME NULL,
  `position` VARCHAR(255) NULL,
  `school_id` INT UNSIGNED NULL,
  `interest` TEXT NULL,
  `gender` ENUM('f', 'm') NULL,
  `nationality` INT UNSIGNED NULL,
  `origin` INT UNSIGNED NULL,
  `avatar` VARCHAR(255) NULL,
  `deleted_date` DATETIME NULL,
  `sis` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`school_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `program` ;

CREATE TABLE IF NOT EXISTS `program` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `level` ENUM('emba', 'mba') NULL,
  `sis` VARCHAR(45) NULL,
  `year` VARCHAR(10) NULL,
  `deleted_date` DATETIME NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_program_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_program_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `creator_id` INT UNSIGNED NOT NULL,
  `nb_module` INT NULL DEFAULT NULL,
  `abstract` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `objectives` TEXT NULL DEFAULT NULL,
  `teaching` TEXT NULL DEFAULT NULL,
  `attendance` TEXT NULL DEFAULT NULL,
  `duration` VARCHAR(128) NULL,
  `notes` TEXT NULL,
  `learning_outcomes` TEXT NULL,
  `deleted_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  `created_date` DATETIME NULL,
  `version` INT NULL,
  `picture` VARCHAR(80) NULL,
  `video_link` TEXT NULL,
  `video_token` TEXT NULL,
  `program_id` INT UNSIGNED NOT NULL,
  `sis` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_1_idx` (`creator_id` ASC),
  INDEX `fk_course_2_idx` (`program_id` ASC),
  CONSTRAINT `fk_course_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_2`
    FOREIGN KEY (`program_id`)
    REFERENCES `program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module` ;

CREATE TABLE IF NOT EXISTS `module` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_workshop_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_workshop_10`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_policy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading_policy` ;

CREATE TABLE IF NOT EXISTS `grading_policy` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `grade` DOUBLE NULL,
  `type` ENUM('LC', 'WG', 'CP', 'IA') NULL,
  `tpl` TINYINT(1) NOT NULL DEFAULT 0,
  `course_id` INT UNSIGNED NULL,
  `mandatory` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_grading_policy_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_grading_policy_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(512) NULL,
  `describe` TEXT NULL,
  `duration` VARCHAR(512) NULL,
  `type` ENUM('LC', 'WG', 'CP', 'IA') NOT NULL,
  `weight` INT NOT NULL DEFAULT 1,
  `course_id` INT UNSIGNED NOT NULL,
  `parent_id` INT UNSIGNED NULL,
  `grading_policy_id` INT UNSIGNED NULL,
  `module_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_1_idx` (`course_id` ASC),
  INDEX `fk_item_3_idx` (`module_id` ASC),
  INDEX `fk_item_2_idx` (`parent_id` ASC),
  INDEX `fk_item_4_idx` (`grading_policy_id` ASC),
  CONSTRAINT `fk_item_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_3`
    FOREIGN KEY (`module_id`)
    REFERENCES `module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_4`
    FOREIGN KEY (`grading_policy_id`)
    REFERENCES `grading_policy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_prog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_prog` ;

CREATE TABLE IF NOT EXISTS `item_prog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `start_date` DATETIME NULL,
  `due_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_prog_1_idx` (`item_id` ASC),
  CONSTRAINT `fk_item_prog_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `videoconf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf` ;

CREATE TABLE IF NOT EXISTS `videoconf` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` TEXT NULL,
  `start_date` DATETIME NULL,
  `duration` INT NULL,
  `archive_token` TEXT NULL,
  `archive_link` TEXT NULL,
  `archive_status` VARCHAR(128) NULL,
  `status` VARCHAR(45) NULL,
  `conversation_id` INT UNSIGNED NULL,
  `item_prog_id` INT UNSIGNED NULL,
  `title` VARCHAR(256) NULL,
  `description` TEXT NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_1_idx` (`conversation_id` ASC),
  INDEX `fk_videoconf_2_idx` (`item_prog_id` ASC),
  CONSTRAINT `fk_videoconf_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videoconf_2`
    FOREIGN KEY (`item_prog_id`)
    REFERENCES `item_prog` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `videoconf_entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_entity` ;

CREATE TABLE IF NOT EXISTS `videoconf_entity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_id` INT UNSIGNED NULL,
  `name` VARCHAR(128) NULL,
  `avatar` VARCHAR(128) NULL,
  `token` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_entity_videoconf_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_entity_videoconf`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `videoconf_invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_invitation` ;

CREATE TABLE IF NOT EXISTS `videoconf_invitation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_entity_id` INT UNSIGNED NULL,
  `firstname` VARCHAR(128) NULL,
  `lastname` VARCHAR(128) NULL,
  `avatar` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `utc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_invitation_videoconf_entity_idx` (`videoconf_entity_id` ASC),
  CONSTRAINT `fk_videoconf_invitation_videoconf_entity`
    FOREIGN KEY (`videoconf_entity_id`)
    REFERENCES `videoconf_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `videoconf_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_admin` ;

CREATE TABLE IF NOT EXISTS `videoconf_admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_id` INT UNSIGNED NULL,
  `user_id` INT NULL,
  `token` TEXT NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_admin_vodeoconf_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_admin_vodeoconf`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resume` ;

CREATE TABLE IF NOT EXISTS `resume` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `subtitle` VARCHAR(255) NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `type` INT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_education_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_education_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professional_experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professional_experience` ;

CREATE TABLE IF NOT EXISTS `professional_experience` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `address` VARCHAR(255) NULL,
  `logo` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professional_experience_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_professional_experience_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

CREATE TABLE IF NOT EXISTS `user_role` (
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_role_2_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material_document` ;

CREATE TABLE IF NOT EXISTS `material_document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(100) NULL,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `source` TEXT NULL,
  `token` VARCHAR(80) NULL,
  `date` DATE NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mterials_documents_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_mterials_documents_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_material_document_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_material_document_relation` ;

CREATE TABLE IF NOT EXISTS `item_material_document_relation` (
  `item_id` INT UNSIGNED NOT NULL,
  `material_document_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_id`, `material_document_id`),
  INDEX `fk_item_material_document_relation_2_idx` (`material_document_id` ASC),
  CONSTRAINT `fk_item_material_document_relation_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_material_document_relation_2`
    FOREIGN KEY (`material_document_id`)
    REFERENCES `material_document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_assignment` ;

CREATE TABLE IF NOT EXISTS `item_assignment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `response` TEXT NULL,
  `item_prog_id` INT UNSIGNED NULL,
  `submit_date` DATETIME NULL,
  INDEX `fk_item_assignment_1_idx` (`item_prog_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_item_assignment_1`
    FOREIGN KEY (`item_prog_id`)
    REFERENCES `item_prog` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language` ;

CREATE TABLE IF NOT EXISTS `language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `language_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language_level` ;

CREATE TABLE IF NOT EXISTS `language_level` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_language` ;

CREATE TABLE IF NOT EXISTS `user_language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  `language_level_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_language_2_idx` (`language_id` ASC),
  INDEX `fk_user_language_3_idx` (`language_level_id` ASC),
  CONSTRAINT `fk_user_language_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_language_2`
    FOREIGN KEY (`language_id`)
    REFERENCES `language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_language_3`
    FOREIGN KEY (`language_level_id`)
    REFERENCES `language_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading` ;

CREATE TABLE IF NOT EXISTS `grading` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `letter` VARCHAR(3) NULL,
  `min` INT NULL,
  `max` INT NULL,
  `grade` DOUBLE NULL,
  `description` TEXT NULL,
  `tpl` TINYINT(1) NOT NULL DEFAULT 0,
  `school_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grading_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_grading_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faq` ;

CREATE TABLE IF NOT EXISTS `faq` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ask` TEXT NULL,
  `answer` TEXT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_faq_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_faq_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thread` ;

CREATE TABLE IF NOT EXISTS `thread` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(512) NULL,
  `user_id` INT UNSIGNED NULL,
  `course_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thread_1_idx` (`course_id` ASC),
  INDEX `fk_thread_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_thread_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `thread_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thread_message` ;

CREATE TABLE IF NOT EXISTS `thread_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` TEXT NULL,
  `user_id` INT UNSIGNED NULL,
  `thread_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thread_message_1_idx` (`user_id` ASC),
  INDEX `fk_thread_message_2_idx` (`thread_id` ASC),
  CONSTRAINT `fk_thread_message_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_message_2`
    FOREIGN KEY (`thread_id`)
    REFERENCES `thread` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail` ;

CREATE TABLE IF NOT EXISTS `mail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mail_group_id` VARCHAR(255) NULL,
  `suject` VARCHAR(512) NULL,
  `content` TEXT NULL,
  `created_date` DATETIME NOT NULL,
  `draft` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mail_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail_user` ;

CREATE TABLE IF NOT EXISTS `mail_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mail_id` INT UNSIGNED NULL,
  `user_id` INT UNSIGNED NULL,
  `mail_group_id` VARCHAR(255) NULL,
  `created_date` DATETIME NOT NULL,
  `deleted_date` DATETIME NULL,
  `read_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user_1_idx` (`mail_id` ASC),
  INDEX `fk_message_user_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_mail_user_1`
    FOREIGN KEY (`mail_id`)
    REFERENCES `mail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mail_receiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail_receiver` ;

CREATE TABLE IF NOT EXISTS `mail_receiver` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('cc','cci','to','from') NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `mail_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_receiver_1_idx` (`user_id` ASC),
  INDEX `fk_message_receiver_2_idx` (`mail_id` ASC),
  CONSTRAINT `fk_message_receiver_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_receiver_2`
    FOREIGN KEY (`mail_id`)
    REFERENCES `mail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mail_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail_doc` ;

CREATE TABLE IF NOT EXISTS `mail_doc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `mail_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maildoc_1_idx` (`mail_id` ASC),
  CONSTRAINT `fk_mail_doc_1`
    FOREIGN KEY (`mail_id`)
    REFERENCES `mail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `course_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_user_relation` ;

CREATE TABLE IF NOT EXISTS `course_user_relation` (
  `user_id` INT UNSIGNED NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `course_id`),
  INDEX `fk_course_user_relation_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_course_user_relation_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_user_relation_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_prog_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_prog_user` ;

CREATE TABLE IF NOT EXISTS `item_prog_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `item_prog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `item_prog_id`),
  INDEX `fk_item_prog_user_relation_1_idx` (`item_prog_id` ASC),
  UNIQUE INDEX `index3` (`item_prog_id` ASC, `user_id` ASC),
  CONSTRAINT `fk_item_prog_user_relation_1`
    FOREIGN KEY (`item_prog_id`)
    REFERENCES `item_prog` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_prog_user_relation_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_grading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_grading` ;

CREATE TABLE IF NOT EXISTS `item_grading` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_prog_user_id` INT UNSIGNED NULL,
  `grade` INT UNSIGNED NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_grading_2_idx` (`item_prog_user_id` ASC),
  CONSTRAINT `fk_item_grading_2`
    FOREIGN KEY (`item_prog_user_id`)
    REFERENCES `item_prog_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

CREATE TABLE IF NOT EXISTS `task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `creator_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendar_1_idx` (`creator_id` ASC),
  CONSTRAINT `fk_calendar_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task_share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task_share` ;

CREATE TABLE IF NOT EXISTS `task_share` (
  `task_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`task_id`, `user_id`),
  INDEX `fk_calendar_share_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_calendar_share_1`
    FOREIGN KEY (`task_id`)
    REFERENCES `task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_share_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_picture` ;

CREATE TABLE IF NOT EXISTS `school_picture` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NULL,
  `token` VARCHAR(80) NULL,
  `name` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_picture_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_school_picture_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_video` ;

CREATE TABLE IF NOT EXISTS `school_video` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(80) NULL,
  `url` TEXT NULL,
  `name` VARCHAR(255) NULL,
  `school_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_video_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_school_video_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_assigment_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_assigment_document` ;

CREATE TABLE IF NOT EXISTS `item_assigment_document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_assigment_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(100) NULL,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `source` TEXT NULL,
  `token` VARCHAR(80) NULL,
  `date` DATE NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_individual_assigment_document_user_1_idx` (`item_assigment_id` ASC),
  CONSTRAINT `fk_individual_assigment_document_1`
    FOREIGN KEY (`item_assigment_id`)
    REFERENCES `item_assignment` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feed` ;

CREATE TABLE IF NOT EXISTS `feed` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `user_id` INT UNSIGNED NULL,
  `link` TEXT NULL,
  `video` VARCHAR(80) NULL,
  `picture` VARCHAR(80) NULL,
  `name_picture` VARCHAR(255) NULL,
  `document` VARCHAR(80) NULL,
  `name_document` VARCHAR(255) NULL,
  `link_title` VARCHAR(255) NULL,
  `link_desc` TEXT NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feed_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_feed_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feed_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feed_comment` ;

CREATE TABLE IF NOT EXISTS `feed_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `user_id` INT UNSIGNED NULL,
  `feed_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feed_comment_1_idx` (`user_id` ASC),
  INDEX `fk_feed_comment_2_idx` (`feed_id` ASC),
  CONSTRAINT `fk_feed_comment_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feed_comment_2`
    FOREIGN KEY (`feed_id`)
    REFERENCES `feed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact` ;

CREATE TABLE IF NOT EXISTS `contact` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  `request_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  `accepted_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_1_idx` (`user_id` ASC),
  INDEX `fk_contact_2_idx` (`contact_id` ASC),
  UNIQUE INDEX `unoque_cantact` (`user_id` ASC, `contact_id` ASC),
  CONSTRAINT `fk_contact_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_2`
    FOREIGN KEY (`contact_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `program_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `program_user_relation` ;

CREATE TABLE IF NOT EXISTS `program_user_relation` (
  `program_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`program_id`, `user_id`),
  INDEX `fk_program_user_relation_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_program_user_relation_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_user_relation_1`
    FOREIGN KEY (`program_id`)
    REFERENCES `program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permission` ;

CREATE TABLE IF NOT EXISTS `permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_permission` ;

CREATE TABLE IF NOT EXISTS `role_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NOT NULL,
  `permission_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_permission_1_idx` (`permission_id` ASC),
  INDEX `fk_role_permission_2_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_permission_1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `role_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_relation` ;

CREATE TABLE IF NOT EXISTS `role_relation` (
  `role_id` INT UNSIGNED NOT NULL,
  `parent_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `parent_id`),
  INDEX `fk_role_relation_2_idx` (`parent_id` ASC),
  CONSTRAINT `fk_role_relation_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_relation_2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `item_assignment_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_assignment_comment` ;

CREATE TABLE IF NOT EXISTS `item_assignment_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `item_assignment_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NULL,
  `read_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_assignment_10_idx` (`item_assignment_id` ASC),
  INDEX `fk_item_assignment_comment_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_item_assignment_10`
    FOREIGN KEY (`item_assignment_id`)
    REFERENCES `item_assignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_assignment_comment_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_policy_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading_policy_grade` ;

CREATE TABLE IF NOT EXISTS `grading_policy_grade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grading_policy_id` INT UNSIGNED NULL,
  `grade` INT UNSIGNED NULL,
  `user_id` INT UNSIGNED NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_grading_20_idx` (`grading_policy_id` ASC),
  INDEX `fk_grading_policy_grade_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_item_grading_20`
    FOREIGN KEY (`grading_policy_id`)
    REFERENCES `grading_policy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grading_policy_grade_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grading_policy_grade_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading_policy_grade_comment` ;

CREATE TABLE IF NOT EXISTS `grading_policy_grade_comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `grading_policy_grade_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_assignment_comment_1_idx` (`user_id` ASC),
  INDEX `fk_item_assignment_100_idx` (`grading_policy_grade_id` ASC),
  CONSTRAINT `fk_item_assignment_100`
    FOREIGN KEY (`grading_policy_grade_id`)
    REFERENCES `grading_policy_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_assignment_comment_10`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item_assignment_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_assignment_relation` ;

CREATE TABLE IF NOT EXISTS `item_assignment_relation` (
  `item_assignment_id` INT UNSIGNED NOT NULL,
  `item_prog_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_assignment_id`, `item_prog_user_id`),
  INDEX `fk_item_assignment_user_2_idx` (`item_prog_user_id` ASC),
  CONSTRAINT `fk_item_assignment_user_1`
    FOREIGN KEY (`item_assignment_id`)
    REFERENCES `item_assignment` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_assignment_user_2`
    FOREIGN KEY (`item_prog_user_id`)
    REFERENCES `item_prog_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `conversation_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conversation_user` ;

CREATE TABLE IF NOT EXISTS `conversation_user` (
  `conversation_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`conversation_id`, `user_id`),
  INDEX `fk_conversation_user_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_conversation_user_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `text` TEXT NULL,
  `token` VARCHAR(80) NULL,
  `is_draft` TINYINT(1) NOT NULL DEFAULT 0,
  `type` INT NULL,
  `conversation_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_message_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `message_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message_user` ;

CREATE TABLE IF NOT EXISTS `message_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_id` INT UNSIGNED NOT NULL,
  `conversation_id` INT UNSIGNED NOT NULL,
  `from_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `read_date` DATETIME NULL,
  `deleted_date` DATETIME NULL,
  `created_date` DATETIME NOT NULL,
  `type` ENUM('R', 'S', 'RS') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user_1_idx` (`message_id` ASC),
  INDEX `fk_message_user_2_idx` (`conversation_id` ASC),
  INDEX `fk_message_user_3_idx` (`from_id` ASC),
  INDEX `fk_message_user_4_idx` (`user_id` ASC),
  CONSTRAINT `fk_message_user_1`
    FOREIGN KEY (`message_id`)
    REFERENCES `message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_2`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_3`
    FOREIGN KEY (`from_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_4`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `videoconf_conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_conversation` ;

CREATE TABLE IF NOT EXISTS `videoconf_conversation` (
  `videoconf_id` INT UNSIGNED NOT NULL,
  `conversation_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`videoconf_id`, `conversation_id`),
  INDEX `fk_videoconf_conversation_1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_videoconf_conversation_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videoconf_conversation_2`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videoconf_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_doc` ;

CREATE TABLE IF NOT EXISTS `videoconf_doc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_id` INT UNSIGNED NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_doc_1_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_doc_1`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `videoconf_archive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_archive` ;

CREATE TABLE IF NOT EXISTS `videoconf_archive` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `archive_token` TEXT NULL,
  `archive_link` TEXT NULL,
  `archive_status` VARCHAR(128) NULL,
  `archive_duration` INT NULL,
  `videoconf_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_archive_1_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_archive_1`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `message_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message_doc` ;

CREATE TABLE IF NOT EXISTS `message_doc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `name` VARCHAR(255) NULL,
  `message_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_doc_1_idx` (`message_id` ASC),
  CONSTRAINT `fk_message_doc_1`
    FOREIGN KEY (`message_id`)
    REFERENCES `message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `like` ;

CREATE TABLE IF NOT EXISTS `like` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `is_like` TINYINT(1) NOT NULL DEFAULT 1,
  `user_id` INT UNSIGNED NOT NULL,
  `feed_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_like_2_idx` (`feed_id` ASC),
  INDEX `fk_like_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_like_2`
    FOREIGN KEY (`feed_id`)
    REFERENCES `feed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dimension` ;

CREATE TABLE IF NOT EXISTS `dimension` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` ENUM('EQ', 'CQ') NOT NULL,
  `describe` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `component` ;

CREATE TABLE IF NOT EXISTS `component` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dimension_id` INT UNSIGNED NOT NULL,
  `describe` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_1_idx` (`dimension_id` ASC),
  CONSTRAINT `fk_component_1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question` ;

CREATE TABLE IF NOT EXISTS `question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `component_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_1_idx` (`component_id` ASC),
  CONSTRAINT `fk_question_1`
    FOREIGN KEY (`component_id`)
    REFERENCES `component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionnaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire` ;

CREATE TABLE IF NOT EXISTS `questionnaire` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NULL,
  `created_date` DATETIME NOT NULL,
  `max_duration` INT NOT NULL DEFAULT 30,
  `max_time` INT NOT NULL DEFAULT 10,
  PRIMARY KEY (`id`),
  INDEX `fk_questionnaire_1_idx` (`item_id` ASC),
  CONSTRAINT `fk_questionnaire_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `questionnaire_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire_question` ;

CREATE TABLE IF NOT EXISTS `questionnaire_question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT UNSIGNED NOT NULL,
  `questionnaire_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questionnaire_1_idx` (`question_id` ASC),
  INDEX `fk_questionnaire_question_1_idx` (`questionnaire_id` ASC),
  CONSTRAINT `fk_questionnaire_question_2`
    FOREIGN KEY (`question_id`)
    REFERENCES `question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaire_question_1`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `questionnaire_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire_user` ;

CREATE TABLE IF NOT EXISTS `questionnaire_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `questionnaire_id` INT UNSIGNED NOT NULL,
  `state` INT NULL,
  `created_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questionnaire_user_1_idx` (`user_id` ASC),
  INDEX `fk_questionnaire_user_2_idx` (`questionnaire_id` ASC),
  CONSTRAINT `fk_questionnaire_user_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaire_user_2`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `scale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scale` ;

CREATE TABLE IF NOT EXISTS `scale` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer` ;

CREATE TABLE IF NOT EXISTS `answer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `questionnaire_user_id` INT UNSIGNED NOT NULL,
  `questionnaire_question_id` INT UNSIGNED NOT NULL,
  `question_id` INT UNSIGNED NOT NULL,
  `peer_id` INT UNSIGNED NOT NULL,
  `scale_id` INT UNSIGNED NOT NULL,
  `type` ENUM('SELF', 'PEER') NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_1_idx` (`questionnaire_user_id` ASC),
  INDEX `fk_answer_2_idx` (`scale_id` ASC),
  INDEX `fk_answer_4_idx` (`questionnaire_question_id` ASC),
  INDEX `fk_answer_3_idx` (`question_id` ASC),
  INDEX `fk_answer_5_idx` (`peer_id` ASC),
  CONSTRAINT `fk_answer_1`
    FOREIGN KEY (`questionnaire_user_id`)
    REFERENCES `questionnaire_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_2`
    FOREIGN KEY (`scale_id`)
    REFERENCES `scale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_3`
    FOREIGN KEY (`question_id`)
    REFERENCES `question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_4`
    FOREIGN KEY (`questionnaire_question_id`)
    REFERENCES `questionnaire_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_5`
    FOREIGN KEY (`peer_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `question_replace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question_replace` ;

CREATE TABLE IF NOT EXISTS `question_replace` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `dimension_scale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dimension_scale` ;

CREATE TABLE IF NOT EXISTS `dimension_scale` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dimension_id` INT UNSIGNED NOT NULL,
  `min` INT NOT NULL,
  `max` INT NOT NULL,
  `describe` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dimension_scale_1_idx` (`dimension_id` ASC),
  CONSTRAINT `fk_dimension_scale_1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_scale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `component_scale` ;

CREATE TABLE IF NOT EXISTS `component_scale` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `component_id` INT UNSIGNED NOT NULL,
  `min` INT NOT NULL,
  `max` INT NOT NULL,
  `describe` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_scale_1_idx` (`component_id` ASC),
  CONSTRAINT `fk_component_scale_1`
    FOREIGN KEY (`component_id`)
    REFERENCES `component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Placeholder table for view `research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `research` (`id` INT, `firstname` INT, `lastname` INT, `avatar` INT, `category` INT, `role` INT, `facette` INT);

-- -----------------------------------------------------
-- View `research`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `research` ;
DROP TABLE IF EXISTS `research`;
CREATE  OR REPLACE SQL SECURITY DEFINER
VIEW `research` AS
    SELECT 
        `u`.`id` AS `id`,
        CONCAT(`u`.`firstname`, ' ', `u`.`lastname`) AS `firstname`,
        CONCAT(`u`.`lastname`, ' ', `u`.`firstname`) AS `lastname`,
        `u`.`avatar` AS `avatar`,
        'user' AS `category`,
        `role`.`name` AS `role`,
        IF((`role`.`id` = 4), 10, 20) AS `facette`
    FROM
        ((`user` `u`
        JOIN `user_role` `us`)
        JOIN `role`)
    WHERE
        ((`us`.`user_id` = `u`.`id`)
            AND (`us`.`role_id` = `role`.`id`)
            AND (`us`.`role_id` IN (4 , 5))) 
    UNION SELECT 
        `c`.`id` AS `id`,
        `c`.`title` AS `title`,
        `p`.`name` AS `name`,
        `c`.`picture` AS `picture`,
        'course' AS `category`,
        '' AS `role`,
        '30' AS `facette`
    FROM
        (`course` `c`
        JOIN `program` `p`)
    WHERE
        (`c`.`program_id` = `p`.`id`) 
    UNION SELECT 
        `s`.`id` AS `id`,
        `s`.`name` AS `name`,
        `s`.`short_name` AS `short_name`,
        `s`.`logo` AS `logo`,
        'school' AS `category`,
        '' AS `role`,
        '40' AS `facette`
    FROM
        `school` `s`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
