-- MySQL Script generated by MySQL Workbench
-- lun. 14 déc. 2015 11:35:32 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apiwow
-- -----------------------------------------------------
-- apiwow

-- -----------------------------------------------------
-- Table `poll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll` ;

CREATE TABLE IF NOT EXISTS `poll` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NULL,
  `expiration_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `poll_question_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll_question_type` ;

CREATE TABLE IF NOT EXISTS `poll_question_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `poll_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll_question` ;

CREATE TABLE IF NOT EXISTS `poll_question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` TEXT NULL,
  `poll_id` INT UNSIGNED NULL,
  `poll_question_type_id` INT UNSIGNED NOT NULL,
  `is_mandatory` TINYINT(1) NOT NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_question_1_idx` (`poll_question_type_id` ASC),
  INDEX `fk_poll_question_2_idx` (`poll_id` ASC),
  INDEX `fk_poll_question_3_idx` (`parent_id` ASC),
  CONSTRAINT `fk_poll_question_1`
    FOREIGN KEY (`poll_question_type_id`)
    REFERENCES `poll_question_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_question_2`
    FOREIGN KEY (`poll_id`)
    REFERENCES `poll` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_question_3`
    FOREIGN KEY (`parent_id`)
    REFERENCES `poll_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `poll_question_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll_question_item` ;

CREATE TABLE IF NOT EXISTS `poll_question_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(256) NULL,
  `poll_question_id` INT UNSIGNED NOT NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_question_item_1_idx` (`poll_question_id` ASC),
  INDEX `fk_poll_question_item_2_idx` (`parent_id` ASC),
  CONSTRAINT `fk_poll_question_item_1`
    FOREIGN KEY (`poll_question_id`)
    REFERENCES `poll_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_question_item_2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `poll_question_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `poll_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll_answer` ;

CREATE TABLE IF NOT EXISTS `poll_answer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `poll_id` INT UNSIGNED NOT NULL,
  `poll_question_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_answer_1_idx` (`poll_question_id` ASC),
  INDEX `fk_poll_answer_2_idx` (`poll_id` ASC),
  INDEX `fk_poll_answer_3_idx` (`user_id` ASC),
  CONSTRAINT `fk_poll_answer_1`
    FOREIGN KEY (`poll_question_id`)
    REFERENCES `poll_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_answer_2`
    FOREIGN KEY (`poll_id`)
    REFERENCES `poll` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_answer_3`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `poll_answer_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll_answer_items` ;

CREATE TABLE IF NOT EXISTS `poll_answer_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `poll_answer_id` INT UNSIGNED NOT NULL,
  `poll_question_item_id` INT UNSIGNED NOT NULL,
  `answer` TEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_answer_items_1_idx` (`poll_answer_id` ASC),
  INDEX `fk_poll_answer_items_2_idx` (`poll_question_item_id` ASC),
  CONSTRAINT `fk_poll_answer_items_1`
    FOREIGN KEY (`poll_answer_id`)
    REFERENCES `poll_answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_answer_items_2`
    FOREIGN KEY (`poll_question_item_id`)
    REFERENCES `poll_question_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

