<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mail\Template\Model\TplModel'           => __DIR__ . '/src/Mail/Template/Model/TplModel.php',
    'Mail\Template\Storage\FsStorage'        => __DIR__ . '/src/Mail/Template/Storage/FsStorage.php',
    'Mail\Template\Storage\AbstractStorage'  => __DIR__ . '/src/Mail/Template/Storage/AbstractStorage.php',
    'Mail\Template\Storage\StorageInterface' => __DIR__ . '/src/Mail/Template/Storage/StorageInterface.php',
    'Mail\Service\Mail'                      => __DIR__ . '/src/Mail/Service/Mail.php',
    'Mail\Mail\Message'                      => __DIR__ . '/src/Mail/Mail/Message.php',
    'Mail\Mime\Part'                         => __DIR__ . '/src/Mail/Mime/Part.php',
);
